In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt



## Introduction to Tensors
### Creating Tensors


In [ ]:
# Scalar
# pytorch tensors are created using torch.tensor()
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                        [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]


tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# Tensor

TENSOR = torch.tensor([[[1, 2,3 ],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape


torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

## Random Tensors
Why random Tensors?

Random tensors are important because the way many neural networks learn is thatthey start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers


In [ ]:
# Create a random tensor of size (3, 4)

random_tensor = torch.rand(3, 4)

random_tensor

tensor([[0.3984, 0.9251, 0.6846, 0.7251],
        [0.3835, 0.4711, 0.5507, 0.8081],
        [0.7571, 0.9081, 0.0143, 0.5043]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a random tensor with similar shape to an image tensor


random_image_size_tensor = torch.rand(size =(3, 224, 224)) # height, width, color cbannels (R, G, B)

random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [ ]:
# Create a tensor fo all zeros

zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones

ones= torch.ones(size = (3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

# Creating a range of tensors and tensors-like

In [ ]:
# USe a torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(start =0, end=11, step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like
ten_zeroes = torch.zeros_like(one_to_ten)
ten_zeroes


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

**Note:** Tensor datatypes is one of the 3 big big errors you wil run into with PyTorch & deep learnning:

1. Tensors not right datatypes
2. Tensors not right shape
3. Tensors not on the right device


In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What dataype is the tensor (e.g float 32 or float 16)
                               device = None, # What device is your tensor on
                               requires_grad = False ) # Weather or not to track gradients with this tensors operation
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.long)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

## Getting information from tensors (tensor attributes)
1. Tensors not right datatypes - to get datatype for a tensor, can use `tensor.dtype`
2. Tensors not right shape - to gte shape from a tenso, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`


In [ ]:
# Create a tensor

some_tensor= torch.rand(3, 4)
some_tensor

tensor([[0.1176, 0.7227, 0.6527, 0.9696],
        [0.2646, 0.4910, 0.4466, 0.3517],
        [0.5491, 0.8881, 0.5496, 0.2535]])

In [ ]:
# Find out details about some tensor

print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")


tensor([[0.1176, 0.7227, 0.6527, 0.9696],
        [0.2646, 0.4910, 0.4466, 0.3517],
        [0.5491, 0.8881, 0.5496, 0.2535]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


## Manioulating Tensors (tensor operations)

Tensor operations include:

1. Addition
2. Subtraction
3. Multiplication (element-wise)
4. Division
5. Matrix Multiplication



In [ ]:
# Create a Tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# multiply tensor by 10
tensor * 10



tensor([10, 20, 30])

In [ ]:
# subtract 10

tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out PyTorch in-built function
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multipliction
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of teh **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`





In [ ]:
torch.matmul(torch.rand(10, 3), torch.rand(3, 10)).shape

torch.Size([10, 10])

In [ ]:
#  Element wise multipliction
print(tensor , "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix Multiplication (dot product)

torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 291 µs, sys: 0 ns, total: 291 µs
Wall time: 298 µs


tensor(14)

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 73 µs, sys: 0 ns, total: 73 µs
Wall time: 78.7 µs


tensor(14)

### One of the most common errors in deep learning is shape errors

In [ ]:
# Shapes for matrix multiplication
tensor_a = torch.tensor([[1, 2],
                         [3, 4],
                          [5, 6]])
tensor_b = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
# torch.mm is the same as torch.matmul



To fix our tensor shape issues, we can manipulate the shape of one of our tensor using as **transpose**

A **transpose** switches teh axes or dimesiopns of a given tensor.


In [ ]:
# The matrix multiplication operation works tensor_b is transposed
print(f"Original shapes: tensor_a = {tensor_a.shape}, tensor_b = {tensor_b.shape}")
print(f"New shapes: tensor-a = {tensor_a.shape}(same shape as above), tensor_b.T = {tensor_b.T.shape}")
print(f"Multiplying: {tensor_a.shape} @ {tensor_b.T.shape} <- inner dimensions must match ")
print('Output: \n')

output = torch.matmul(tensor_a, tensor_b.T)

print(output)
print(f"\nOutput shape: {output.shape}")


Original shapes: tensor_a = torch.Size([3, 2]), tensor_b = torch.Size([3, 2])
New shapes: tensor-a = torch.Size([3, 2])(same shape as above), tensor_b.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match 
Output: 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


### Find the min, max, mean, sum etc (tensor aggregation)



In [ ]:
# Create a tensor
x =torch.arange(0, 100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()


(tensor(450), tensor(450))

## Finding the positional min and max

In [ ]:
# Find the position in tensor that has the minimum value with argmin() \n
# And the maximum value at the position with argmax()
# return index position of the target tensor where the  minimum and maximum value occurs
x.argmin(), x.argmax()

(tensor(0), tensor(9))

## Reshaping, stacking, squeezing and unsqeezing tensors
* Reshaping - reshapes an input te sor to defined shape
* View - Return a view of an input tensor of certain shape but keep the same memoru as the original tensor
* Stacking - Combine multiple tensors on top of each other (vstack) or side by side (hsatck)
* Squeee - removes all `1` dimesions from a tensor
* Unsqeeze - add a `1` dimensions to a target tensor
* Permute- Return a view of the input with dimensipns oermuted (swapped) in a certain way

In [ ]:
# Lets create a tensor
import torch
x = torch.arange(1., 10.)
x , x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.squeeze() removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds a single dimensions to a target tensor at a specifi dim(dimensions)

print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Adds an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
# torch.permute - rearranges the dimensions of the target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [Height, Width, coolor_channels]

# Permute the original tensor to rearrange te axis (or dim) order

x_permuted = x_original.permute(2, 0, 1) # shifts axis 0 -> 1, 1 -> 2, 2 -> 0

In [ ]:
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Selecting data from tensors (indexing)

Indexing with pytorch is similar to indexing with numpy.

In [ ]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
# Lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Lets index on te middle bracket (dim = 1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
# Lets index on the most inner bracket (last dimensions)
x[0][2][2]

tensor(9)

In [ ]:
# You can also use ':' to select 'all' of the target dimension
x[:, :, 1]

tensor([[2, 5, 8]])

## Pytorch tensors and NumPy

Numpy is a popular scientific Python numerial computing library.

And because of this, Pytorch has functionality to interact with it.

* Data in NumPy, want in pytorch tensor -> `torch.from_numpy(ndarray)`
* Pytorch tensor -> Numpy -> `torch.tensor.numpy()`

In [ ]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
# When converting from numpy to pytorch, pytorch reflects numpy's deault datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [ ]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to Numpy array

tensor= torch.ones(7)
numpy_tensor = tensor.numpy()

tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility ( trying to take random out of random )

In short how a neural network learns:

`starts with random numbers -> tensor operations -> update random nuhmbers to try and make them better representation of the data -> again -> again -> again....`

To reduce the randomness in neural networks and Pytorch comes the comcept of a **random Seed**.

Essentially what the random seed does is "flavour" the ranodmness

In [ ]:
import torch
# create two random tensors:

random_tensor_a = torch.rand(3, 4)
random_tensor_b = torch.rand(3, 4)

print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a == random_tensor_b)

tensor([[0.6582, 0.7933, 0.7759, 0.3087],
        [0.9889, 0.9079, 0.5846, 0.9680],
        [0.0515, 0.7207, 0.1081, 0.0764]])
tensor([[0.7253, 0.7060, 0.7095, 0.9732],
        [0.5880, 0.9830, 0.7901, 0.5367],
        [0.2357, 0.7913, 0.3674, 0.9524]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Lets make some random but reproducible tensors

import torch

# set the ranodm seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3, 4)

print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c == random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and Pytorch objects on GPUs ( and making aster computations)

GPUs = Faster computaton on numbers, thanks to CUDA = NIVIDIA hardware + pytorch working behind the scenes to make everything good

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device


'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1